// lib/deployments.ts
// Static deployment history for the ArcVane Studio project timeline.
// Data sourced from Vercel deployment records.

export interface Deployment {
  date: string; // ISO date YYYY-MM-DD
  branch: string;
  pr?: number;
  commit: string;
  message: string;
  environment: "Production" | "Preview";
  author: string;
  previewUrl: string;
}

export const deployments: Deployment[] = [
  // === Jun 18, 2026 ===
  {
    date: "2026-06-18",
    branch: "main",
    pr: 44,
    commit: "af62b65",
    message: "Merge pull request #44 from Big-jpg/landing/streamline-sections",
    environment: "Production",
    author: "atom-rossf",
    previewUrl: "https://arcvane-studio.com",
  },
  {
    date: "2026-06-18",
    branch: "landing/streamline-sections",
    pr: 44,
    commit: "f1d3f28",
    message: "landing: remove apparatus, materials CTA, one final thought; make cards clickable, remove price and start evening button",
    environment: "Preview",
    author: "atom-rossf",
    previewUrl: "https://arcvane-studio-git-landing-streamline-sections-big-team.vercel.app",
  },
  {
    date: "2026-06-18",
    branch: "main",
    pr: 43,
    commit: "f3e1929",
    message: "Merge pull request #43 from Big-jpg/copy-reduction/product-detail-chapters",
    environment: "Production",
    author: "big-jpg",
    previewUrl: "https://arcvane-studio-f3e1929-big-team.vercel.app",
  },
  {
    date: "2026-06-18",
    branch: "main",
    pr: 42,
    commit: "bc56d98",
    message: "Merge pull request #42 from Big-jpg/copy-reduction/public-pages",
    environment: "Production",
    author: "big-jpg",
    previewUrl: "https://arcvane-studio-bc56d98-big-team.vercel.app",
  },
  {
    date: "2026-06-18",
    branch: "copy-reduction/product-detail-chapters",
    pr: 43,
    commit: "7e6888c",
    message: "copy: condense product detail and chapter panel text",
    environment: "Preview",
    author: "big-jpg",
    previewUrl: "https://arcvane-studio-git-copy-reduction-product-detail-chapters-big-team.vercel.app",
  },
  {
    date: "2026-06-18",
    branch: "copy-reduction/public-pages",
    pr: 42,
    commit: "823e3e1",
    message: "copy: remove redundant text from collection and landing pages",
    environment: "Preview",
    author: "big-jpg",
    previewUrl: "https://arcvane-studio-git-copy-reduction-public-pages-big-team.vercel.app",
  },
  {
    date: "2026-06-18",
    branch: "main",
    pr: 41,
    commit: "13597ca",
    message: "Merge pull request #41 from Big-jpg/feature/finish-ambient-tonality",
    environment: "Production",
    author: "atom-rossf",
    previewUrl: "https://arcvane-studio-13597ca-big-team.vercel.app",
  },
  {
    date: "2026-06-18",
    branch: "feature/finish-ambient-tonality",
    pr: 41,
    commit: "865208e",
    message: "feat: ambient tonality overlay on product pages",
    environment: "Preview",
    author: "atom-rossf",
    previewUrl: "https://arcvane-studio-git-feature-finish-ambient-tonality-big-team.vercel.app",
  },
  // === Jun 13, 2026 ===
  {
    date: "2026-06-13",
    branch: "main",
    commit: "1cea087",
    message: "Refine mobile product and chapter layouts",
    environment: "Production",
    author: "manus",
    previewUrl: "https://arcvane-studio-1cea087-big-team.vercel.app",
  },
  // === Jun 12, 2026 ===
  {
    date: "2026-06-12",
    branch: "main",
    commit: "422a436",
    message: "Refresh materials page with richer studies and onward CTAs",
    environment: "Production",
    author: "manus",
    previewUrl: "https://arcvane-studio-422a436-big-team.vercel.app",
  },
  {
    date: "2026-06-12",
    branch: "main",
    commit: "ba9c084",
    message: "Guide the landing flow through materials and collection",
    environment: "Production",
    author: "manus",
    previewUrl: "https://arcvane-studio-ba9c084-big-team.vercel.app",
  },
  {
    date: "2026-06-12",
    branch: "main",
    commit: "24e43bb",
    message: "Guide landing CTAs through the home scroll story",
    environment: "Production",
    author: "manus",
    previewUrl: "https://arcvane-studio-24e43bb-big-team.vercel.app",
  },
  // === Jun 5, 2026 ===
  {
    date: "2026-06-05",
    branch: "main",
    pr: 40,
    commit: "90b5152",
    message: "Merge pull request #40 from Big-jpg/refinement-pass-1",
    environment: "Production",
    author: "manus-ai",
    previewUrl: "https://arcvane-studio-90b5152-big-team.vercel.app",
  },
  {
    date: "2026-06-05",
    branch: "refinement-pass-1",
    pr: 40,
    commit: "8305c49",
    message: "Strip back product clarity UI",
    environment: "Preview",
    author: "manus-ai",
    previewUrl: "https://arcvane-studio-git-refinement-pass-1-big-team.vercel.app",
  },
  {
    date: "2026-06-05",
    branch: "refinement-pass-1",
    pr: 40,
    commit: "213032d",
    message: "Align trust copy across product scope",
    environment: "Preview",
    author: "manus-ai",
    previewUrl: "https://arcvane-studio-213032d-big-team.vercel.app",
  },
  {
    date: "2026-06-05",
    branch: "main",
    pr: 39,
    commit: "8256910",
    message: "Merge pull request #39 from Big-jpg/compliance-phase-1",
    environment: "Production",
    author: "manus",
    previewUrl: "https://arcvane-studio-8256910-big-team.vercel.app",
  },
  // === Jun 4, 2026 ===
  {
    date: "2026-06-04",
    branch: "compliance-phase-1",
    pr: 39,
    commit: "0ac23ee",
    message: "Phase 7: separate physical and electrical supply models",
    environment: "Preview",
    author: "manus",
    previewUrl: "https://arcvane-studio-git-compliance-phase-1-big-team.vercel.app",
  },
  {
    date: "2026-06-04",
    branch: "main",
    pr: 38,
    commit: "29a01ac",
    message: "Merge pull request #38 from Big-jpg/rebuild-b5-polish",
    environment: "Production",
    author: "manus-agent",
    previewUrl: "https://arcvane-studio-29a01ac-big-team.vercel.app",
  },
  {
    date: "2026-06-04",
    branch: "rebuild-b5-polish",
    pr: 38,
    commit: "549d570",
    message: "Polish time-state storefront validation",
    environment: "Preview",
    author: "manus-agent",
    previewUrl: "https://arcvane-studio-git-rebuild-b5-polish-big-team.vercel.app",
  },
  {
    date: "2026-06-04",
    branch: "rebuild-b4-product-cards",
    pr: 37,
    commit: "7mKzEGEaW",
    message: "Rebuild product cards with time-state theming",
    environment: "Preview",
    author: "manus-agent",
    previewUrl: "https://arcvane-studio-git-rebuild-b4-product-cards-big-team.vercel.app",
  },
  {
    date: "2026-06-04",
    branch: "rebuild-b3-nav-palette-materials",
    pr: 35,
    commit: "FRMACzY9f",
    message: "Rebuild nav, palette system, and materials page",
    environment: "Preview",
    author: "manus-agent",
    previewUrl: "https://arcvane-studio-git-rebuild-b3-nav-palette-materials-big-team.vercel.app",
  },
  // === Jun 3, 2026 ===
  {
    date: "2026-06-03",
    branch: "rebuild-b2-homepage",
    pr: 27,
    commit: "BaUaF1NCg",
    message: "Rebuild homepage with scroll-driven time-state chapters",
    environment: "Preview",
    author: "manus",
    previewUrl: "https://arcvane-studio-git-rebuild-b2-homepage-big-team.vercel.app",
  },
  {
    date: "2026-06-03",
    branch: "rebuild-b1-timestate-infra",
    pr: 26,
    commit: "EAyBHnRLt",
    message: "Rebuild time-state infrastructure and CSS variable system",
    environment: "Preview",
    author: "manus",
    previewUrl: "https://arcvane-studio-git-rebuild-b1-timestate-infra-big-team.vercel.app",
  },
  // === Jun 1, 2026 ===
  {
    date: "2026-06-01",
    branch: "codex/admin-lite-catalogue-wizard",
    pr: 25,
    commit: "5HCuyH9ih",
    message: "Admin lite catalogue wizard",
    environment: "Preview",
    author: "Big-jpg",
    previewUrl: "https://arcvane-studio-git-codex-admin-lite-catalogue-wizard-big-team.vercel.app",
  },
  // === May 31, 2026 ===
  {
    date: "2026-05-31",
    branch: "codex/public-ia-cleanup",
    pr: 21,
    commit: "GTdD7mRWs",
    message: "Public IA cleanup",
    environment: "Preview",
    author: "Big-jpg",
    previewUrl: "https://arcvane-studio-git-codex-public-ia-cleanup-big-team.vercel.app",
  },
  {
    date: "2026-05-31",
    branch: "codex/atelier-experience-v2",
    pr: 19,
    commit: "BNJMZQbKW",
    message: "Atelier experience v2",
    environment: "Preview",
    author: "Big-jpg",
    previewUrl: "https://arcvane-studio-git-codex-atelier-experience-v2-big-team.vercel.app",
  },
  {
    date: "2026-05-31",
    branch: "codex/db-setup-parity",
    pr: 18,
    commit: "3k51cLKvW",
    message: "Database setup parity",
    environment: "Preview",
    author: "Big-jpg",
    previewUrl: "https://arcvane-studio-git-codex-db-setup-parity-big-team.vercel.app",
  },
  // === May 25, 2026 ===
  {
    date: "2026-05-25",
    branch: "rebuild-a5-cleanup",
    pr: 17,
    commit: "2LEhj9zUG",
    message: "Rebuild A5: cleanup pass",
    environment: "Preview",
    author: "big-jpg",
    previewUrl: "https://arcvane-studio-git-rebuild-a5-cleanup-big-team.vercel.app",
  },
  {
    date: "2026-05-25",
    branch: "rebuild-a4-pages",
    pr: 16,
    commit: "DnXHtpYwh",
    message: "Rebuild A4: pages structure",
    environment: "Preview",
    author: "manus",
    previewUrl: "https://arcvane-studio-git-rebuild-a4-pages-big-team.vercel.app",
  },
  {
    date: "2026-05-25",
    branch: "rebuild-a3-homepage",
    pr: 15,
    commit: "7oUXtbP3M",
    message: "Rebuild A3: homepage",
    environment: "Preview",
    author: "manus",
    previewUrl: "https://arcvane-studio-git-rebuild-a3-homepage-big-team.vercel.app",
  },
  {
    date: "2026-05-25",
    branch: "rebuild-a2-catalogue-data",
    pr: 14,
    commit: "3rtDhzJa6",
    message: "Rebuild A2: catalogue data layer",
    environment: "Preview",
    author: "manus-ai",
    previewUrl: "https://arcvane-studio-git-rebuild-a2-catalogue-data-big-team.vercel.app",
  },
  {
    date: "2026-05-25",
    branch: "rebuild-a1-palette-header-footer",
    pr: 13,
    commit: "DEJ9Tb4fh",
    message: "Rebuild A1: palette, header, and footer",
    environment: "Preview",
    author: "big-jpg",
    previewUrl: "https://arcvane-studio-git-rebuild-a1-palette-header-footer-big-team.vercel.app",
  },
  // === May 24, 2026 ===
  {
    date: "2026-05-24",
    branch: "fix-product-save-500",
    pr: 12,
    commit: "HoJ1BjkWL",
    message: "Fix product save 500 error",
    environment: "Preview",
    author: "atom-rossf",
    previewUrl: "https://arcvane-studio-git-fix-product-save-500-big-team.vercel.app",
  },
  {
    date: "2026-05-24",
    branch: "admin-lite-image-fix",
    pr: 11,
    commit: "9iNWreVBy",
    message: "Admin lite image fix",
    environment: "Preview",
    author: "manus-ai",
    previewUrl: "https://arcvane-studio-git-admin-lite-image-fix-big-team.vercel.app",
  },
  {
    date: "2026-05-24",
    branch: "admin-lite-products",
    pr: 10,
    commit: "E9StGnWNf",
    message: "Admin lite products interface",
    environment: "Preview",
    author: "manus",
    previewUrl: "https://arcvane-studio-git-admin-lite-products-big-team.vercel.app",
  },
  {
    date: "2026-05-24",
    branch: "admin-lite-bom-phase2",
    pr: 9,
    commit: "3eLceqZsg",
    message: "Admin lite BOM phase 2",
    environment: "Preview",
    author: "big-jpg",
    previewUrl: "https://arcvane-studio-git-admin-lite-bom-phase2-big-team.vercel.app",
  },
  {
    date: "2026-05-24",
    branch: "admin-lite-bom-phase1",
    pr: 8,
    commit: "BonCCJ2J2",
    message: "Admin lite BOM phase 1",
    environment: "Preview",
    author: "manus",
    previewUrl: "https://arcvane-studio-git-admin-lite-bom-phase1-big-team.vercel.app",
  },
  // === May 15, 2026 ===
  {
    date: "2026-05-15",
    branch: "phase-10-testing-deployment",
    pr: 7,
    commit: "B2A7Ey3AX",
    message: "Phase 10: testing and deployment",
    environment: "Preview",
    author: "atom-rossf",
    previewUrl: "https://arcvane-studio-git-phase-10-testing-deployment-big-team.vercel.app",
  },
  // === May 14, 2026 ===
  {
    date: "2026-05-14",
    branch: "phase-9-fitting-guide-and-trust",
    pr: 6,
    commit: "RXAa9pnXm",
    message: "Phase 9: fitting guide and trust pages",
    environment: "Preview",
    author: "atom-rossf",
    previewUrl: "https://arcvane-studio-git-phase-9-fitting-guide-and-trust-big-team.vercel.app",
  },
  {
    date: "2026-05-14",
    branch: "phase-8-admin-lite",
    pr: 5,
    commit: "4d9KATuQG",
    message: "Phase 8: admin lite panel",
    environment: "Preview",
    author: "atom-rossf",
    previewUrl: "https://arcvane-studio-git-phase-8-admin-lite-big-team.vercel.app",
  },
  {
    date: "2026-05-14",
    branch: "phase-7-buyer-hooks",
    pr: 4,
    commit: "8JMu6F1vJ",
    message: "Phase 7: buyer hooks and cart",
    environment: "Preview",
    author: "atom-rossf",
    previewUrl: "https://arcvane-studio-git-phase-7-buyer-hooks-big-team.vercel.app",
  },
  // === May 12, 2026 ===
  {
    date: "2026-05-12",
    branch: "phase-6-stripe-checkout",
    pr: 4,
    commit: "2dYTKxUaS",
    message: "Phase 6: Stripe checkout integration",
    environment: "Preview",
    author: "atom-rossf",
    previewUrl: "https://arcvane-studio-git-phase-6-stripe-checkout-big-team.vercel.app",
  },
  // === May 11, 2026 ===
  {
    date: "2026-05-11",
    branch: "phase-4-db-procedures",
    pr: 3,
    commit: "5WA7egLRQ",
    message: "Phase 4: database procedures",
    environment: "Preview",
    author: "Big-jpg",
    previewUrl: "https://arcvane-studio-git-phase-4-db-procedures-big-team.vercel.app",
  },
  {
    date: "2026-05-11",
    branch: "phase-5-auth",
    pr: 2,
    commit: "BVbRAGzLC",
    message: "Phase 5: authentication",
    environment: "Preview",
    author: "atom-rossf",
    previewUrl: "https://lumenform-git-fork-atom-rossf-phase-5-auth-big-team.vercel.app",
  },
];
