// lib/mock-bom.ts

import { calculateBomTotal, calculateGrossMargin } from "./bom-calculations";
import type { BomComponent, ProductBomLine, ProductBomSummary } from "./bom-types";

export const bomComponents: BomComponent[] = [
  {
    id: "comp-pla-matte-white",
    name: "PLA filament - matte white",
    category: "Filament",
    unit: "kg",
    unitCost: 29,
    currency: "AUD",
    supplier: null,
    notes: "General-purpose matte PLA for warm white shade bodies.",
  },
  {
    id: "comp-pla-translucent-clear",
    name: "PLA filament - translucent clear",
    category: "Filament",
    unit: "kg",
    unitCost: 34,
    currency: "AUD",
    supplier: null,
    notes: "Translucent PLA for diffuser-oriented designs.",
  },
  {
    id: "comp-silk-pla-blue",
    name: "Silk PLA - blue",
    category: "Filament",
    unit: "kg",
    unitCost: 36,
    currency: "AUD",
    supplier: null,
    notes: "Decorative silk PLA for high-sheen variants.",
  },
  {
    id: "comp-e27-holder-au",
    name: "AU certified E27 socket holder",
    category: "Adapter",
    unit: "each",
    unitCost: 4.8,
    currency: "AUD",
    supplier: null,
    notes: "Representative costing placeholder only; not a procurement source of truth.",
  },
  {
    id: "comp-b22-holder-au",
    name: "AU certified B22 socket holder",
    category: "Adapter",
    unit: "each",
    unitCost: 4.6,
    currency: "AUD",
    supplier: null,
    notes: "Representative costing placeholder only; not a procurement source of truth.",
  },
  {
    id: "comp-led-bulb-low-heat",
    name: "Low-heat LED bulb",
    category: "Electrical",
    unit: "each",
    unitCost: 5.5,
    currency: "AUD",
    supplier: null,
    notes: "Optional low-heat LED placeholder for later product bundles; not supplied in current decorative-component listings.",
  },
  {
    id: "comp-bearing-608",
    name: "608 bearing",
    category: "Bearing",
    unit: "each",
    unitCost: 1.35,
    currency: "AUD",
    supplier: null,
    notes: "Mechanical component seed for future non-shade products.",
  },
  {
    id: "comp-m3-heat-set-insert",
    name: "M3 heat-set insert",
    category: "Fastener",
    unit: "each",
    unitCost: 0.18,
    currency: "AUD",
    supplier: null,
    notes: null,
  },
  {
    id: "comp-packaging-box",
    name: "Packaging box",
    category: "Packaging",
    unit: "each",
    unitCost: 1.9,
    currency: "AUD",
    supplier: null,
    notes: "Single retail dispatch box.",
  },
  {
    id: "comp-assembly-labour",
    name: "Assembly labour",
    category: "Labour",
    unit: "hour",
    unitCost: 35,
    currency: "AUD",
    supplier: null,
    notes: "Internal labour costing placeholder.",
  },
  {
    id: "comp-print-machine-time",
    name: "Print machine time",
    category: "Machine time",
    unit: "hour",
    unitCost: 3.5,
    currency: "AUD",
    supplier: null,
    notes: "Machine depreciation, maintenance, and energy placeholder.",
  },
];

export const productBomLines: ProductBomLine[] = [
  {
    id: "bom-prod-02-filament",
    productId: "prod-02",
    componentId: "comp-silk-pla-blue",
    lineType: "material",
    quantity: 0.28,
    unit: "kg",
    unitCost: 36,
    wastagePercent: 8,
    sortOrder: 10,
    notes: "Primary shade body filament allowance.",
  },
  {
    id: "bom-prod-02-e27-adapter",
    productId: "prod-02",
    componentId: "comp-e27-holder-au",
    lineType: "material",
    quantity: 1,
    unit: "each",
    unitCost: 4.8,
    wastagePercent: 0,
    sortOrder: 20,
    notes: "Representative default adapter inclusion.",
  },
  {
    id: "bom-prod-02-packaging",
    productId: "prod-02",
    componentId: "comp-packaging-box",
    lineType: "packaging",
    quantity: 1,
    unit: "each",
    unitCost: 1.9,
    wastagePercent: 0,
    sortOrder: 30,
    notes: null,
  },
  {
    id: "bom-prod-02-labour",
    productId: "prod-02",
    componentId: "comp-assembly-labour",
    lineType: "labour",
    quantity: 0.18,
    unit: "hour",
    unitCost: 35,
    wastagePercent: 0,
    sortOrder: 40,
    notes: "Inspection, adapter fit check, and packing.",
  },
  {
    id: "bom-prod-02-machine",
    productId: "prod-02",
    componentId: "comp-print-machine-time",
    lineType: "machine",
    quantity: 7.5,
    unit: "hour",
    unitCost: 3.5,
    wastagePercent: 0,
    sortOrder: 50,
    notes: "Nominal print runtime for costing visibility.",
  },
  {
    id: "bom-prod-03-filament",
    productId: "prod-03",
    componentId: "comp-pla-matte-white",
    lineType: "material",
    quantity: 0.32,
    unit: "kg",
    unitCost: 29,
    wastagePercent: 10,
    sortOrder: 10,
    notes: "Primary petal body filament allowance.",
  },
  {
    id: "bom-prod-03-b22-adapter",
    productId: "prod-03",
    componentId: "comp-b22-holder-au",
    lineType: "material",
    quantity: 1,
    unit: "each",
    unitCost: 4.6,
    wastagePercent: 0,
    sortOrder: 20,
    notes: "Representative default adapter inclusion.",
  },
  {
    id: "bom-prod-03-heat-set-inserts",
    productId: "prod-03",
    componentId: "comp-m3-heat-set-insert",
    lineType: "material",
    quantity: 3,
    unit: "each",
    unitCost: 0.18,
    wastagePercent: 5,
    sortOrder: 30,
    notes: "Seed line for small hardware costing.",
  },
  {
    id: "bom-prod-03-packaging",
    productId: "prod-03",
    componentId: "comp-packaging-box",
    lineType: "packaging",
    quantity: 1,
    unit: "each",
    unitCost: 1.9,
    wastagePercent: 0,
    sortOrder: 40,
    notes: null,
  },
  {
    id: "bom-prod-03-labour",
    productId: "prod-03",
    componentId: "comp-assembly-labour",
    lineType: "labour",
    quantity: 0.25,
    unit: "hour",
    unitCost: 35,
    wastagePercent: 0,
    sortOrder: 50,
    notes: "Petal inspection, adapter fit check, and packing.",
  },
  {
    id: "bom-prod-03-machine",
    productId: "prod-03",
    componentId: "comp-print-machine-time",
    lineType: "machine",
    quantity: 8.75,
    unit: "hour",
    unitCost: 3.5,
    wastagePercent: 0,
    sortOrder: 60,
    notes: "Nominal print runtime for costing visibility.",
  },
];

export function getBomComponent(componentId: string): BomComponent | undefined {
  return bomComponents.find((component) => component.id === componentId);
}

export function getBomLinesForProduct(productId: string): ProductBomLine[] {
  return productBomLines
    .filter((line) => line.productId === productId)
    .sort((a, b) => a.sortOrder - b.sortOrder);
}

export function getProductBomSummary(
  productId: string,
  price: number,
  currency: string,
): ProductBomSummary {
  const lines = getBomLinesForProduct(productId);
  const totalCost = calculateBomTotal(lines);

  return {
    productId,
    currency,
    lineCount: lines.length,
    totalCost,
    grossMarginPercent: calculateGrossMargin(price, totalCost),
  };
}
