// lib/mock-products.ts
import { PRODUCT_CATEGORIES } from "./product-options";
import type { Product } from "./types";

export const products: Product[] = [
  {
    id: "prod-01",
    handle: "shell-fan",
    title: "Shell Fan",
    price: 90,
    currency: "AUD",
    category: "Single Shades",
    description:
      "A clear PLA shell-fan diffuser with a coral-like rim that gathers warm LED light along its ribs and releases it as a soft edge glow across nearby walls.",
    material: "Clear PLA, translucent shell-diffusion finish",
    dimensions: "Ø 280mm × H 210mm",
    colours: ["Clear PLA", "Shell"],
    images: ["/products/product-01.png"],
    adapters: ["E27"],
    inStock: true,
    shopifyProductId: null,
    shopifyVariantId: null,
    designFamily: "Shell Fan",
    metadata: null,
  },
  {
    id: "prod-02",
    handle: "coral-veil",
    title: "Coral Veil",
    price: 90,
    currency: "AUD",
    category: "Single Shades",
    description:
      "A translucent ribbed shell diffuser that catches warm LED light along its edge and softens it through layered clear PLA, leaving a quiet coral-veil texture in the room.",
    material: "Translucent PLA, fine ribbed diffusion finish",
    dimensions: "Ø 270mm × H 220mm",
    colours: ["Clear PLA", "Coastal Blue"],
    images: ["/products/product-02.png"],
    adapters: ["E27"],
    inStock: true,
    shopifyProductId: null,
    shopifyVariantId: null,
    designFamily: "Coral Veil",
    metadata: null,
  },
  {
    id: "prod-03",
    handle: "dune-rib",
    title: "Dune Rib",
    price: 90,
    currency: "AUD",
    category: "Single Shades",
    description:
      "A striated dune-inspired shade whose close ribs temper direct glare and turn the LED source into bands of sand-coloured shadow and gentle downward warmth.",
    material: "PLA, matte striated dune finish",
    dimensions: "Ø 260mm × H 190mm",
    colours: ["Sand", "Limestone"],
    images: ["/products/product-03.png"],
    adapters: ["E27"],
    inStock: true,
    shopifyProductId: null,
    shopifyVariantId: null,
    designFamily: "Dune Rib",
    metadata: null,
  },
  {
    id: "prod-04",
    handle: "limestone-bloom",
    title: "Limestone Bloom",
    price: 140,
    currency: "AUD",
    category: "Table Lamps",
    description:
      "A complete table lamp pairing a limestone-toned bloom diffuser with a matte tripod stand, designed to pool warm LED light across a bedside table without a hard exposed source.",
    material: "PLA diffuser with matte PLA tripod stand",
    dimensions: "Ø 240mm × H 340mm",
    colours: ["Limestone", "Shell", "Warm Amber"],
    images: ["/products/product-04.png"],
    adapters: ["E27"],
    inStock: true,
    shopifyProductId: null,
    shopifyVariantId: null,
    designFamily: "Limestone Bloom",
    metadata: null,
  },
  {
    id: "prod-05",
    handle: "tidepool-diffuser",
    title: "Tidepool Diffuser",
    price: 90,
    currency: "AUD",
    category: "Single Shades",
    description:
      "An organic pooling form in clear PLA that holds brightness near the socket and lets the light drift outward through thicker and thinner tidepool-like edges.",
    material: "Clear PLA, variable-opacity organic diffusion finish",
    dimensions: "Ø 255mm × H 175mm",
    colours: ["Clear PLA", "Shell", "Coastal Blue"],
    images: ["/products/product-05.png"],
    adapters: ["E27"],
    inStock: true,
    shopifyProductId: null,
    shopifyVariantId: null,
    designFamily: "Tidepool Diffuser",
    metadata: null,
  },
  {
    id: "prod-06",
    handle: "beach-post-tripod",
    title: "Beach Post Tripod",
    price: 55,
    currency: "AUD",
    category: "Accessories",
    description:
      "A matte tripod stand with a weathered beach-post feel, giving compatible E27 diffusers a stable table-lamp base and a softer tactile contrast to translucent shades.",
    material: "Matte PLA, soft-touch tripod stand finish",
    dimensions: "Ø 180mm footprint × H 165mm",
    colours: ["Sand", "Limestone"],
    images: ["/products/product-06.png"],
    adapters: ["E27"],
    inStock: true,
    shopifyProductId: null,
    shopifyVariantId: null,
    designFamily: "Beach Post Tripod",
    metadata: null,
  },
  {
    id: "prod-07",
    handle: "amber-ember-set",
    title: "Amber Ember Set",
    price: 120,
    currency: "AUD",
    category: "Shade Sets",
    description:
      "A three-piece shade set in warm amber tones, tuned for layered domestic glow so each diffuser catches the LED differently and builds a low sunset-like rhythm across a room.",
    material: "Translucent PLA, warm amber diffusion finish",
    dimensions: "3 shades, each approx. Ø 220–260mm × H 160–200mm",
    colours: ["Warm Amber", "Sand", "Shell"],
    images: ["/products/product-07.png"],
    adapters: ["E27"],
    inStock: true,
    shopifyProductId: null,
    shopifyVariantId: null,
    designFamily: "Amber Ember Set",
    metadata: null,
  },
  {
    id: "prod-08",
    handle: "clear-pla-coastal-set",
    title: "Clear PLA Coastal Set",
    price: 150,
    currency: "AUD",
    category: "Shade Sets",
    description:
      "A five-piece clear PLA diffuser set that explores shell, rib, dune, and tidepool surfaces, giving one shared E27 lighting system a coordinated range of soft optical effects.",
    material: "Clear PLA, mixed coastal diffusion finishes",
    dimensions: "5 shades, each approx. Ø 200–280mm × H 150–220mm",
    colours: ["Clear PLA", "Shell", "Limestone"],
    images: ["/products/product-08.png"],
    adapters: ["E27"],
    inStock: true,
    shopifyProductId: null,
    shopifyVariantId: null,
    designFamily: "Clear PLA Coastal Set",
    metadata: null,
  },
];

export function getProductByHandle(handle: string): Product | undefined {
  return products.find((p) => p.handle === handle);
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category);
}

export const categories = PRODUCT_CATEGORIES;
